name: release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: release
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout invoice-shelf code
        uses: actions/checkout@v4
        with:
          repository: InvoiceShelf/InvoiceShelf

      - name: checkout module code
        uses: actions/checkout@v4
        with:
          path: Modules/WhiteLabel

      - name: install invoice-shelf dependencies
        run: npm install && npm run build

      - name: build module package
        run: bash ./Modules/WhiteLabel/scripts/artifact-gen.sh

      - name: check package
        run: ls -lah
