name: release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: release
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout invoice-shelf code
        uses: actions/checkout@v4
        with:
          repository: InvoiceShelf/InvoiceShelf

      - name: install invoice-shelf dependencies
        run: npm install && npm run build

      #      - name: checkout module code
      #        uses: actions/checkout@v4
      #        with:
      #          path: Modules/WhiteLabel
      #
      #      - name:
      #
      #      #      - name: check tree
      #      #        run: cd Modules/WhiteLabel/ && bash ./scripts/artifact-gen.sh
